spring:
  application:
    name: SimpleEcommerceApplication
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceApplicationDatabase
    username: hamza
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090
